# Basic
title: f8-button
email: imalitavakoli@gmail.com
description: Awesome collection of CSS3 Buttons for those who love good design. All-in-One solution for any webpage. Variety of colors, effects, states, and sizes.
baseurl: /docs
url: https://imalitavakoli.github.io/f8-button


# Social
author:             imalitavakoli
twitter_username:   imalitavakoli
facebook_username:  imalitavakoli


# Build settings
destination:        ../docs/
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
